# Dependencies
# markdown: redcarpet
# highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Financially Millennial
tagline: "Becoming financially independent for the avocado toast"
description: "Becoming financially savvy"
url: BW0ng.github.io
baseurl: /

author:
  name: "Brandon Wong"
  url: https://twitter.com/BW0ng

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/BW0ng

plugins:
  - jekyll-gist
  - jekyll-paginate
